// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/aa/auth": {
            "post": {
                "description": "Sends a transaction with the given EIP-7702 auth message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccountAbstract"
                ],
                "summary": "Sends EIP-7702 transaction",
                "operationId": "aaAuthSend",
                "parameters": [
                    {
                        "description": "Standard EIP-7702 auth message",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SetCodeAuth"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction hash",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/aa/auth/{txHash}": {
            "get": {
                "description": "Query the EIP-7702 auth result of given transaction hash. Note, if transaction not found (code 1001), user could send a transaction again.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccountAbstract"
                ],
                "summary": "Query EIP-7702 auth result",
                "operationId": "aaAuthStatus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "EIP-7702 transaction hash",
                        "name": "txHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Auth result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.SetCodeResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.BusinessError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code error code, 0 indicates success, otherwise business error (e.g. user not found) or internal server error.",
                    "type": "integer"
                },
                "data": {
                    "description": "Data is the return value if success. Otherwise, it is concret failure reason in string type."
                },
                "message": {
                    "description": "Message error message associated with ` + "`" + `Code` + "`" + `.",
                    "type": "string"
                }
            }
        },
        "api.SetCodeAuth": {
            "type": "object",
            "required": [
                "contract",
                "r",
                "s"
            ],
            "properties": {
                "chainId": {
                    "type": "integer"
                },
                "contract": {
                    "type": "string"
                },
                "nonce": {
                    "type": "integer"
                },
                "r": {
                    "type": "string"
                },
                "s": {
                    "type": "string"
                },
                "v": {
                    "type": "integer"
                }
            }
        },
        "api.SetCodeResult": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "failure reason",
                    "type": "string"
                },
                "executed": {
                    "description": "whether tx executed",
                    "type": "boolean"
                },
                "success": {
                    "description": "whether set code successfully",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
