// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/aa/gastank/config": {
            "get": {
                "description": "Returns the configuration of the gas tank paymaster.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GasTank"
                ],
                "summary": "Get gas tank paymaster configuration",
                "operationId": "aaGasTankConfig",
                "responses": {
                    "200": {
                        "description": "Gas tank paymaster configuration",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.GasTankConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/aa/gastank/sign": {
            "post": {
                "description": "Calculates maxTokenCost for the given UserOperation, adds paymaster signature, and returns reassembled paymasterData.\nEncoding format (129 bytes): token(20) || maxTokenCost(32) || validAfter(6) || validUntil(6) || signature(65). maxTokenCost is hex encoded.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GasTank"
                ],
                "summary": "Sign paymasterData for UserOperation",
                "operationId": "aaGasTankSign",
                "parameters": [
                    {
                        "description": "UserOperation for maxTokenCost estimation and paymaster signing",
                        "name": "userOp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UserOperation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Signed and reassembled paymasterData",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/aa/gastank/stub": {
            "post": {
                "description": "Returns paymasterData used for user operation gas estimation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GasTank"
                ],
                "summary": "Prepare paymasterData for gas estimation",
                "operationId": "aaGasTankStub",
                "parameters": [
                    {
                        "description": "Paymaster data stub request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GasTankStubRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paymaster address and data (0x-prefixed hex)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.PaymasterAndDataStub"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/aa/paymaster/config": {
            "get": {
                "description": "Returns the configuration of the verifying paymaster.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Paymaster"
                ],
                "summary": "Get verifying paymaster configuration",
                "operationId": "aaPaymasterConfig",
                "responses": {
                    "200": {
                        "description": "Verifying paymaster configuration",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.VerifyingPaymasterConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/aa/paymaster/sign": {
            "post": {
                "description": "Validates the given UserOperation, adds paymaster signature, and returns reassembled paymasterData.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Paymaster"
                ],
                "summary": "Sign paymasterData of given user operation and return reassembled paymasterData",
                "operationId": "aaPaymasterSign",
                "parameters": [
                    {
                        "description": "UserOperation for paymaster signing",
                        "name": "userOp",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UserOperation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Signed and reassembled paymasterData (0x-prefixed hex)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/aa/paymaster/stub": {
            "post": {
                "description": "Returns the stub paymasterData of verifying paymaster for gas estimation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Paymaster"
                ],
                "summary": "Returns the stub paymasterData of verifying paymaster for gas estimation",
                "operationId": "aaPaymasterStub",
                "parameters": [
                    {
                        "description": "Verifying paymaster stub request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VerifyingPaymasterStubRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paymaster address and data (0x-prefixed hex)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.PaymasterAndDataStub"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tokenpay/config": {
            "get": {
                "description": "Returns the supported ERC20 token list and the configured recipient address for token-pay.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TokenPay"
                ],
                "summary": "Get token-pay configuration",
                "operationId": "tokenPayConfig",
                "responses": {
                    "200": {
                        "description": "Token-pay configuration",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.TokenPayConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tokenpay/price": {
            "get": {
                "description": "Returns the ETH price quoted in the specified token, i.e. how many token units are required for 1 ETH.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TokenPay"
                ],
                "summary": "Get ETH price by token",
                "operationId": "tokenPayGetETHPrice",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ERC20 token address (0x-prefixed, 42 characters)",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ETH price in token smallest units",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tokenpay/submit": {
            "post": {
                "description": "Submits two raw transactions (transfer token and business) for sponsored execution.\nBackend validates both transactions first. If validation passes, it sends a funding ETH transaction.\nAfter funding is confirmed asynchronously, backend broadcasts transfer-token tx then business tx.\nClients can poll on-chain status of both submitted transactions (transfer-token and business) by their tx hashes.\nThe whole flow is considered completed only when both transactions are successfully executed.\nIf transfer-token execution fails, the user may be blacklisted by risk control.\nIf transactions remain pending for a long time, contact administrator for investigation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TokenPay"
                ],
                "summary": "Submit token-pay transactions",
                "operationId": "tokenPaySubmit",
                "parameters": [
                    {
                        "description": "Raw transfer-token tx and raw business tx",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TokenPayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Submission accepted",
                        "schema": {
                            "$ref": "#/definitions/api.BusinessError"
                        }
                    },
                    "600": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.BusinessError"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.BusinessError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code error code, 0 indicates success, otherwise business error (e.g. user not found) or internal server error.",
                    "type": "integer"
                },
                "data": {
                    "description": "Data is the return value if success. Otherwise, it is concret failure reason in string type."
                },
                "message": {
                    "description": "Message error message associated with ` + "`" + `Code` + "`" + `.",
                    "type": "string"
                }
            }
        },
        "api.GasTankConfig": {
            "type": "object",
            "properties": {
                "paymaster": {
                    "description": "Paymaster is the address of the gas tank paymaster contract.",
                    "type": "string"
                },
                "tokens": {
                    "description": "Tokens is the list of ERC20 token contracts that could be used for gas fee payment.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.GasTankStubRequest": {
            "type": "object",
            "required": [
                "sender",
                "token"
            ],
            "properties": {
                "sender": {
                    "description": "Smart account address in hex format with 0x prefix.",
                    "type": "string"
                },
                "token": {
                    "description": "ERC20 token address to pay gas fee.",
                    "type": "string"
                }
            }
        },
        "api.PaymasterAndDataStub": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                }
            }
        },
        "api.TokenPayConfig": {
            "type": "object",
            "properties": {
                "maxGasCost": {
                    "description": "MaxGasCost is the maximum allowed gas cost in wei.",
                    "type": "integer"
                },
                "minGasFeeRatio": {
                    "description": "MinGasFeeRatio is the minimum allowed gas fee ratio (gas fee / base fee) in percentage. For example, 120 means the gas fee must be at least 120% of the base fee.",
                    "type": "integer"
                },
                "minGasTipRatio": {
                    "description": "MinGasTipRatio is the minimum allowed gas tip ratio (priority fee / base fee) in percentage. For example, 20 means the priority fee must be at least 20% of the base fee.",
                    "type": "integer"
                },
                "recipient": {
                    "description": "Recipient is the configured recipient address that receives token payments.",
                    "type": "string"
                },
                "suggestedGasPriceBumpRatio": {
                    "description": "SuggestedGasPriceBumpRatio is the percentage by which to bump the suggested gas price to increase the chance of timely inclusion in blocks.",
                    "type": "integer"
                },
                "suggestedTokenPriceBumpRatio": {
                    "description": "SuggestedTokenPriceBumpRatio is the percentage by which to bump the suggested token price to increase the chance of timely inclusion in blocks when the price is volatile.",
                    "type": "integer"
                },
                "tokens": {
                    "description": "Tokens is the list of ERC20 token contracts supported for token-pay. Note, the tokens[0] is the default USDT token used for quoting and payment.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.TokenPayRequest": {
            "type": "object",
            "required": [
                "rawBusinessTx",
                "rawTransferTokenTx"
            ],
            "properties": {
                "rawBusinessTx": {
                    "type": "string"
                },
                "rawTransferTokenTx": {
                    "type": "string"
                }
            }
        },
        "api.UserOperation": {
            "type": "object",
            "required": [
                "callData",
                "callGasLimit",
                "maxFeePerGas",
                "maxPriorityFeePerGas",
                "nonce",
                "paymaster",
                "paymasterData",
                "paymasterPostOpGasLimit",
                "paymasterVerificationGasLimit",
                "preVerificationGas",
                "sender",
                "signature",
                "verificationGasLimit"
            ],
            "properties": {
                "callData": {
                    "type": "string",
                    "minLength": 2
                },
                "callGasLimit": {
                    "type": "string",
                    "maxLength": 32
                },
                "factory": {
                    "type": "string"
                },
                "factoryData": {
                    "type": "string",
                    "minLength": 2
                },
                "maxFeePerGas": {
                    "type": "string",
                    "maxLength": 32
                },
                "maxPriorityFeePerGas": {
                    "type": "string",
                    "maxLength": 32
                },
                "nonce": {
                    "type": "string"
                },
                "paymaster": {
                    "description": "Paymaster",
                    "type": "string"
                },
                "paymasterData": {
                    "description": "at least validAfter (6) || validUntil (6) || signature (65)",
                    "type": "string",
                    "minLength": 156
                },
                "paymasterPostOpGasLimit": {
                    "type": "string",
                    "maxLength": 32
                },
                "paymasterVerificationGasLimit": {
                    "type": "string",
                    "maxLength": 32
                },
                "preVerificationGas": {
                    "type": "string",
                    "maxLength": 32
                },
                "sender": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "verificationGasLimit": {
                    "type": "string",
                    "maxLength": 32
                }
            }
        },
        "api.VerifyingPaymasterConfig": {
            "type": "object",
            "properties": {
                "contractWhitelist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "maxGasCost": {
                    "type": "integer"
                },
                "smartAccountWhitelist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.VerifyingPaymasterStubRequest": {
            "type": "object",
            "required": [
                "delegation",
                "sender"
            ],
            "properties": {
                "delegation": {
                    "description": "Delegated contract address in hex format with 0x prefix. Set to non-zero value if user op carries a 7702 auth message.",
                    "type": "string"
                },
                "sender": {
                    "description": "Smart account address in hex format with 0x prefix.",
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Provides paymaster services for gas fee sponsorship.",
            "name": "Paymaster"
        },
        {
            "description": "Provides an off-chain gas tank sponsorship service for smart accounts, including paymaster data preparation and user operation signing for on-chain paymaster contract validation.",
            "name": "GasTank"
        },
        {
            "description": "Provides gas fee sponsorship so EOA accounts can pay gas fees with supported ERC20 tokens.",
            "name": "TokenPay"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Fluent Backend API",
	Description:      "Fluent Backend provides account abstraction, gas tank paymaster, and ERC20 token gas payment services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
